program: run_test.py
method: bayes
metric:
  name: Accuracy_validation
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  optimizer:
    values: ["adam", "sgd"]
  batch_size_p2p:
    distribution: q_log_uniform_values
    q: 8
    min: 64
    max: 256
  lr_p2p:
    min: 0.0001
    max: 0.1

  fl_rounds_server:
    min: 1
    max: 10
  local_training_epochs_server:
    min: 1
    max: 2
  batch_size_server:
    distribution: q_log_uniform_values
    q: 8
    min: 64
    max: 256
  lr_server:
    min: 0.0001
    max: 0.1
    
command:
  - ${env}
  - poetry 
  - run 
  - python
  - ${program}
  - --config 
  - p2p+server_0.8.json
  - ${args}
