program: run_test.py
method: random
metric:
  name: Accuracy_validation
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  optimizer:
    values: ["adam", "sgd"]
  lr_server:
    min: 0.0001
    max: 0.1
  batch_size:
    distribution: q_log_uniform_values
    q: 8
    min: 64
    max: 256

command:
  - ${env}
  - poetry 
  - run 
  - python
  - ${program}
  - --config 
  - private_06.json
  - ${args}
