program: run_test.py
method: random
metric:
  name: Accuracy_validation
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  optimizer:
    values: ["adam", "sgd"]
  lr_server:
    min: 0.0001
    max: 0.1
  batch_size:
    distribution: q_log_uniform_values
    q: 8
    min: 64
    max: 256
  batch_size_p2p:
    distribution: q_log_uniform_values
    q: 8
    min: 64
    max: 256
  fl_rounds_P2P:
    min: 1
    max: 10
  local_training_epochs_p2p:
    min: 1
    max: 4
  lr_p2p:
    min: 0.0001
    max: 0.1
    
command:
  - ${env}
  - poetry 
  - run 
  - python
  - ${program}
  - --config 
  - p2p+server_0.2.json
  - ${args}
